// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuMHINMTjkEhPc6kVIxqQo51y7vm7E1OU',
    appId: '1:553626588075:web:278fa3771fb96c7381b8ee',
    messagingSenderId: '553626588075',
    projectId: 'once-again-e1f4b',
    authDomain: 'once-again-e1f4b.firebaseapp.com',
    storageBucket: 'once-again-e1f4b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR21SV-xchg2uJqQsUBI108EDnYAl7--g',
    appId: '1:553626588075:android:8ab97784358e3bc681b8ee',
    messagingSenderId: '553626588075',
    projectId: 'once-again-e1f4b',
    storageBucket: 'once-again-e1f4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKkByuojVSyCqSlRu6oyC-GdX2aPEkNdI',
    appId: '1:553626588075:ios:d0bd14ff77c4b9c581b8ee',
    messagingSenderId: '553626588075',
    projectId: 'once-again-e1f4b',
    storageBucket: 'once-again-e1f4b.appspot.com',
    iosBundleId: 'com.example.onceAgain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKkByuojVSyCqSlRu6oyC-GdX2aPEkNdI',
    appId: '1:553626588075:ios:e64814dcb7d2467581b8ee',
    messagingSenderId: '553626588075',
    projectId: 'once-again-e1f4b',
    storageBucket: 'once-again-e1f4b.appspot.com',
    iosBundleId: 'com.example.onceAgain.RunnerTests',
  );
}
